### ISSUE TITLE
Unhandled exception if username and/or password not set

### ISSUE THREAD

**Issue by xoxys** [SISheogorath/readme-to-dockerhub#109]
As this exception does not exit with a non-zero exit code, CI's will pass anyway:

```
node:1) UnhandledPromiseRejectionWarning: Error: Both username and password must be passed to this function!
    at Object.<anonymous> (/app/node_modules/docker-hub-api/src/api.js:48:29)
    at new Promise (<anonymous>)
    at Object.login (/app/node_modules/docker-hub-api/src/api.js:44:20)
    at Object.<anonymous> (/app/index.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by xoxys** [comment]
Thanks
